---
apiVersion: v1
kind: Namespace
metadata:
  name: mongodb
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mongodb
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongodb
    spec:
      containers:
      - image: docker.io/georgechiu/agent-java8
        name: mongodb
        env:
        - name: COLOR
          value: "blue"
        resources: {}
---
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mongodb
  name: mongodb
spec:
  type: NodePort
  ports:
  - port: 32545
    protocol: TCP
    targetPort: 32545
    nodePort: 32545
  selector:
    app: mongodb
---

